version: '3'
services:
    flashcardpro-app:
        container_name: flashcardpro-app
        build:
            context: ./docker/8.4
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWGROUP: '${WWWGROUP:-1000}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

networks:
    sail:
        driver: bridge
